package com.example.data.obd

import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

data class ComponentHealth(
    val componentId: String,
    val componentNameAr: String,
    val componentNameEn: String,
    val score: Int,
    val statusAr: String,
    val statusEn: String,
    val recommendationAr: String,
    val recommendationEn: String,
    val colorHex: String
)

data class ServiceIntervalPrediction(
    val oilChangeRemainingKm: Int,
    val oilChangeRemainingDays: Int,
    val oilChangeConfidence: Int,
    val dieselFilterRemainingKm: Int,
    val dieselFilterRemainingDays: Int,
    val dieselFilterConfidence: Int,
    val airFilterRemainingKm: Int,
    val cabinFilterRemainingKm: Int,
    val predictionExplanationAr: String,
    val predictionExplanationEn: String
)

data class EngineHealthReport(
    val overallScore: Int,
    val components: List<ComponentHealth>,
    val analysisSummaryAr: String,
    val analysisSummaryEn: String,
    val lastAnalysisTimestamp: Long,
    val isRealAi: Boolean, // True if generated by Gemini, False if generated by local rules
    val servicePrediction: ServiceIntervalPrediction
)

object GeminiHealthPredictor {

    fun calculateLocalServicePrediction(currentData: ObdSensorData): ServiceIntervalPrediction {
        val hasP1186 = currentData.activeDtcs.any { it.code == "P1186" || it.code == "P1188" }
        val oilRemaining = currentData.oilRemainingKm
        val oilDays = (oilRemaining / 35).coerceAtLeast(1)
        val oilConfidence = when {
            oilRemaining > 5000 -> 95
            oilRemaining > 2000 -> 88
            else -> 72
        }

        val dieselRemaining = when {
            hasP1186 -> 400
            currentData.fuelPressure < 200 && currentData.isEngineRunning -> 3200
            currentData.dpfSootLevel > 80 -> 6500
            else -> 11800
        }
        val dieselDays = (dieselRemaining / 35).coerceAtLeast(1)
        val dieselConfidence = if (hasP1186) 98 else 85

        val airRemaining = if (currentData.dpfSootLevel > 70) 3800 else 7900
        val cabinRemaining = 9200

        val explanationAr = if (hasP1186) {
            "تحذير: تم رصد كود عطل في نظام ضغط الديزل (P1186). يوصى باستبدال فلتر الديزل على الفور لحماية البخاخات."
        } else {
            "تم حساب عمر فلتر الديزل وزيت المحرك بناءً على أنماط القيادة والضغوط المقاسة لتفادي الانسداد."
        }

        val explanationEn = if (hasP1186) {
            "Warning: Active diesel pressure fault code (P1186). Immediate replacement of the diesel filter is highly recommended to protect injectors."
        } else {
            "Service intervals calculated based on engine load cycles and pressure patterns. Daily average driving is estimated at 35 km."
        }

        return ServiceIntervalPrediction(
            oilChangeRemainingKm = oilRemaining,
            oilChangeRemainingDays = oilDays,
            oilChangeConfidence = oilConfidence,
            dieselFilterRemainingKm = dieselRemaining,
            dieselFilterRemainingDays = dieselDays,
            dieselFilterConfidence = dieselConfidence,
            airFilterRemainingKm = airRemaining,
            cabinFilterRemainingKm = cabinRemaining,
            predictionExplanationAr = explanationAr,
            predictionExplanationEn = explanationEn
        )
    }

    fun parseEngineHealthReport(jsonStr: String, currentData: ObdSensorData, timestamp: Long, isRealAi: Boolean): EngineHealthReport {
        val cleanJson = jsonStr.trim()
            .removePrefix("```json")
            .removePrefix("```")
            .removeSuffix("```")
            .trim()

        return try {
            val obj = JSONObject(cleanJson)
            val overallScore = obj.optInt("overallScore", 90)
            val componentsArray = obj.optJSONArray("components")
            val componentsList = mutableListOf<ComponentHealth>()

            if (componentsArray != null) {
                for (i in 0 until componentsArray.length()) {
                    val compObj = componentsArray.getJSONObject(i)
                    componentsList.add(
                        ComponentHealth(
                            componentId = compObj.optString("componentId", ""),
                            componentNameAr = compObj.optString("componentNameAr", ""),
                            componentNameEn = compObj.optString("componentNameEn", ""),
                            score = compObj.optInt("score", 95),
                            statusAr = compObj.optString("statusAr", ""),
                            statusEn = compObj.optString("statusEn", ""),
                            recommendationAr = compObj.optString("recommendationAr", ""),
                            recommendationEn = compObj.optString("recommendationEn", ""),
                            colorHex = compObj.optString("colorHex", "#4CAF50")
                        )
                    )
                }
            }

            val summaryAr = obj.optString("analysisSummaryAr", "")
            val summaryEn = obj.optString("analysisSummaryEn", "")

            val predObj = obj.optJSONObject("servicePrediction")
            val servicePrediction = if (predObj != null) {
                ServiceIntervalPrediction(
                    oilChangeRemainingKm = predObj.optInt("oilChangeRemainingKm", currentData.oilRemainingKm),
                    oilChangeRemainingDays = predObj.optInt("oilChangeRemainingDays", (currentData.oilRemainingKm / 35).coerceAtLeast(1)),
                    oilChangeConfidence = predObj.optInt("oilChangeConfidence", 90),
                    dieselFilterRemainingKm = predObj.optInt("dieselFilterRemainingKm", 11200),
                    dieselFilterRemainingDays = predObj.optInt("dieselFilterRemainingDays", 320),
                    dieselFilterConfidence = predObj.optInt("dieselFilterConfidence", 85),
                    airFilterRemainingKm = predObj.optInt("airFilterRemainingKm", 8200),
                    cabinFilterRemainingKm = predObj.optInt("cabinFilterRemainingKm", 9400),
                    predictionExplanationAr = predObj.optString("predictionExplanationAr", "تحليل الصيانة الذكي نشط عبر جميناي"),
                    predictionExplanationEn = predObj.optString("predictionExplanationEn", "Intelligent service tracking active via Gemini AI")
                )
            } else {
                calculateLocalServicePrediction(currentData)
            }

            EngineHealthReport(
                overallScore = overallScore,
                components = componentsList,
                analysisSummaryAr = summaryAr,
                analysisSummaryEn = summaryEn,
                lastAnalysisTimestamp = timestamp,
                isRealAi = isRealAi,
                servicePrediction = servicePrediction
            )
        } catch (e: Exception) {
            Log.e("GeminiHealthPredictor", "JSON parsing failure: ${e.message}", e)
            calculateLocalRuleHealth(emptyList(), currentData)
        }
    }

    fun calculateLocalRuleHealth(history: List<ObdSensorData>, currentData: ObdSensorData): EngineHealthReport {
        val latest = currentData
        val nowTime = System.currentTimeMillis()
        
        // 1. Cooling system
        val coolingScore = when {
            latest.coolantTemp >= 102 -> 25
            latest.coolantTemp >= 96 -> 60
            latest.coolantTemp < 45 -> 75 // Cold engine
            else -> 96
        }
        val coolingStatusAr = when {
            coolingScore <= 30 -> "حرج (سخونة مفرطة)"
            coolingScore <= 70 -> "تحذير (حرارة مرتفعة)"
            else -> "سليم"
        }
        val coolingStatusEn = when {
            coolingScore <= 30 -> "Critical (Overheating)"
            coolingScore <= 70 -> "Warning (High Temp)"
            else -> "Healthy"
        }
        val coolingRecAr = when {
            coolingScore <= 30 -> "تحذير حاد: درجة حرارة مبرد المحرك بلغت ${latest.coolantTemp}م مئوية! أوقف تشغيل السيارة فوراً لتجنب تلف رأس المحرك وافحص مياه الرديتر ومروحة التبريد."
            coolingScore <= 70 -> "ملاحظة: حرارة المحرك مرتفعة نسبياً (${latest.coolantTemp}م). قد يشير ذلك إلى بداية نقص في سائل التبريد أو ضعف خفيف في أداء الثرموستات."
            else -> "نظام التبريد يعمل بكفاءة ممتازة، درجة الحرارة الحالية ${latest.coolantTemp}م وهي ضمن المدى الطبيعي والمثالي للمحرك."
        }
        val coolingRecEn = when {
            coolingScore <= 30 -> "CRITICAL WARNING: Coolant temperature reached ${latest.coolantTemp}°C! Stop the vehicle immediately to prevent severe engine head damage. Inspect coolant level and radiator fans."
            coolingScore <= 70 -> "NOTICE: Engine is running warm (${latest.coolantTemp}°C). This might indicate early coolant leakage or thermostat restriction."
            else -> "The cooling system is operating optimally. Current temperature is ${latest.coolantTemp}°C, which is within the ideal operating range."
        }
        val coolingColor = when {
            coolingScore <= 30 -> "#F44336"
            coolingScore <= 70 -> "#FFC107"
            else -> "#4CAF50"
        }

        // 2. Lubrication system
        val isRunning = latest.isEngineRunning
        val lubricationScore = when {
            isRunning && latest.oilPressure < 1.0 -> 15
            isRunning && latest.oilPressure < 1.8 -> 55
            latest.oilLifePercent <= 15 -> 40
            else -> latest.oilLifePercent
        }
        val lubStatusAr = when {
            lubricationScore <= 30 -> "حرج (ضغط زيت منخفض)"
            lubricationScore <= 70 -> "تنبيه صيانة"
            else -> "سليم"
        }
        val lubStatusEn = when {
            lubricationScore <= 30 -> "Critical (Low Oil)"
            lubricationScore <= 70 -> "Maintenance Due"
            else -> "Healthy"
        }
        val lubRecAr = when {
            isRunning && latest.oilPressure < 1.0 -> "خطر جسيم: ضغط زيت المحرك منخفض جداً (${latest.oilPressure} بار)! قد يتسبب ذلك في احتكاك الأجزاء المعدنية وتصلب المحرك. أوقف المحرك فوراً وافحص مستوى الزيت."
            latest.oilLifePercent <= 15 -> "تنبيه صيانة: عمر الزيت المتبقي هو ${latest.oilLifePercent}% ومتبقي له ${latest.oilRemainingKm} كم. يرجى التخطيط لاستبدال زيت المحرك والفلتر في أقرب وقت."
            else -> "نظام التزييت مستقر. ضغط الزيت هو ${latest.oilPressure} بار وعمر الزيت المتبقي هو ${latest.oilLifePercent}% (${latest.oilRemainingKm} كم متبقية)."
        }
        val lubRecEn = when {
            isRunning && latest.oilPressure < 1.0 -> "GRAVE DANGER: Oil pressure is extremely low (${latest.oilPressure} Bar)! Running the engine will cause catastrophic failure. Turn off engine immediately and inspect oil level."
            latest.oilLifePercent <= 15 -> "MAINTENANCE ALERT: Engine oil life is at ${latest.oilLifePercent}% with ${latest.oilRemainingKm} km remaining. Schedule an oil and filter replacement soon."
            else -> "Lubrication is healthy. Oil pressure is ${latest.oilPressure} Bar and oil life is at ${latest.oilLifePercent}% (${latest.oilRemainingKm} km remaining)."
        }
        val lubColor = when {
            lubricationScore <= 30 -> "#F44336"
            lubricationScore <= 70 -> "#FFC107"
            else -> "#4CAF50"
        }

        // 3. Electrical & Alternator
        val electricalScore = when {
            isRunning && latest.batteryVoltage < 13.0 -> 30
            !isRunning && latest.batteryVoltage < 11.8 -> 45
            else -> 95
        }
        val elecStatusAr = when {
            electricalScore <= 40 -> "عطل في المولد"
            electricalScore <= 70 -> "بطارية ضعيفة"
            else -> "سليم"
        }
        val elecStatusEn = when {
            electricalScore <= 40 -> "Alternator Failure"
            electricalScore <= 70 -> "Weak Battery"
            else -> "Healthy"
        }
        val elecRecAr = when {
            isRunning && latest.batteryVoltage < 13.0 -> "عطل الشحن: جهد البطارية أثناء الدوران هو ${latest.batteryVoltage} فولت فقط، مما يشير إلى توقف دينامو الشحن (Alternator) عن تغذية النظام. افحص سير الدينامو أو الفحمات فوراً."
            !isRunning && latest.batteryVoltage < 11.8 -> "ضعف البطارية: جهد البطارية في وضع السكون منخفض جداً (${latest.batteryVoltage} فولت). قد تجد صعوبة في تشغيل السيارة صباحاً. ينصح بفحص خلايا البطارية واستبدالها."
            else -> "النظام الكهربائي مستقر وجيد جداً. جهد البطارية الحالي هو ${latest.batteryVoltage} فولت، ودينامو الشحن يغذي البطارية بالشكل المثالي."
        }
        val elecRecEn = when {
            isRunning && latest.batteryVoltage < 13.0 -> "CHARGING SYSTEM FAILURE: Battery voltage is only ${latest.batteryVoltage}V while running, indicating the alternator is not charging. Check the drive belt or alternator regulator."
            !isRunning && latest.batteryVoltage < 11.8 -> "WEAK BATTERY: Static battery voltage is low (${latest.batteryVoltage}V). You may experience starting issues. Battery testing or replacement is recommended."
            else -> "Electrical system is healthy and stable. Current voltage is ${latest.batteryVoltage}V. Alternator is charging correctly."
        }
        val elecColor = when {
            electricalScore <= 40 -> "#F44336"
            electricalScore <= 70 -> "#FFC107"
            else -> "#4CAF50"
        }

        // 4. Fuel System CRDi
        val hasP1186 = latest.activeDtcs.any { it.code == "P1186" || it.code == "P1188" }
        val fuelScore = when {
            hasP1186 -> 40
            isRunning && latest.fuelPressure < 200 -> 50
            else -> 93
        }
        val fuelStatusAr = when {
            fuelScore <= 45 -> "خلل في نظام CRDi"
            fuelScore <= 70 -> "تراجع كفاءة ضغط الوقود"
            else -> "سليم"
        }
        val fuelStatusEn = when {
            fuelScore <= 45 -> "CRDi Rail Malfunction"
            fuelScore <= 70 -> "Low Fuel Pressure Performance"
            else -> "Healthy"
        }
        val fuelRecAr = when {
            hasP1186 -> "تنبيه كود P1186/P1188: تم الكشف عن عطل في منظم ضغط الوقود أو انخفاض حاد في ضغط خط السكك المشتركة (Common Rail). ينصح بشدة باستبدال فلتر ديزل السيارة وفحص المنظم الكهربائي لتجنب انطفاء المحرك المفاجئ."
            isRunning && latest.fuelPressure < 200 -> "ملاحظة: ضغط ديزل السكك المشتركة أقل من المتوقع عند التشغيل (${latest.fuelPressure} بار). افحص كفاءة مضخة الديزل الكهربائية وفلتر الوقود."
            else -> "نظام حقن ديزل السكك المشتركة (CRDi) يعمل بضغط وقود مثالي متجاوب يبلغ ${latest.fuelPressure} بار تبعا لسرعة دوران المحرك وحمله."
        }
        val fuelRecEn = when {
            hasP1186 -> "CODE ALERT P1186/P1188: Detected fuel pressure regulator malfunction or minimum rail pressure limit reached. It is highly recommended to replace the fuel filter and test the regulator to prevent stalling under load."
            isRunning && latest.fuelPressure < 200 -> "NOTICE: Common Rail fuel pressure is below normal idle threshold (${latest.fuelPressure} Bar). Check fuel filter or low-pressure fuel pump delivery."
            else -> "The Common Rail Fuel Injection System is operating perfectly with a dynamic fuel pressure of ${latest.fuelPressure} Bar matching demand."
        }
        val fuelColor = when {
            fuelScore <= 45 -> "#F44336"
            fuelScore <= 70 -> "#FFC107"
            else -> "#4CAF50"
        }

        // 5. DPF System
        val hasP2002 = latest.activeDtcs.any { it.code == "P2002" }
        val dpfScore = when {
            hasP2002 -> 35
            latest.dpfSootLevel >= 80 -> 40
            latest.dpfSootLevel >= 50 -> 65
            else -> 92
        }
        val dpfStatusAr = when {
            dpfScore <= 45 -> "انسداد حرج لفلتر جزيئات ديزل DPF"
            dpfScore <= 70 -> "تراكم سخام مرتفع"
            else -> "سليم"
        }
        val dpfStatusEn = when {
            dpfScore <= 45 -> "Critical DPF Restriction"
            dpfScore <= 70 -> "High Soot Accumulation"
            else -> "Healthy"
        }
        val dpfRecAr = when {
            hasP2002 -> "تحذير انسداد DPF (كود P2002): كفاءة فلتر جزيئات الديزل منخفضة جداً بسبب امتلاء قنوات الفلتر بالكربون والرماد (${latest.dpfSootLevel}%). يتطلب ذلك تفعيل دورة تجديد إجبارية بالكمبيوتر أو تنظيف الفلتر بالكامل لتجنب فقدان العزم التام."
            latest.dpfSootLevel >= 50 -> "تحذير: تراكم السخام بالفلتر مرتفع (${latest.dpfSootLevel}%). تجنب الرحلات القصيرة التي تمنع التجديد التلقائي، وقم بقيادة السيارة على الطريق السريع بسرعة مستقرة (RPM فوق 2500) لمدة 20 دقيقة لبدء التجديد."
            else -> "فلتر جزيئات ديزل البيئة (DPF) سليم ونظيف، نسبة تراكم السخام الحالية منخفضة جداً (${latest.dpfSootLevel}%) ولا تتطلب أي إجراء صيانة حالياً."
        }
        val dpfRecEn = when {
            hasP2002 -> "DPF FAULT DETECTED (Code P2002): Diesel Particulate Filter efficiency is severely restricted (${latest.dpfSootLevel}% soot). Requires forced stationary regeneration via scan tool or manual ultrasonic filter cleaning."
            latest.dpfSootLevel >= 50 -> "WARNING: Soot accumulation is elevated (${latest.dpfSootLevel}%). Avoid short drive cycles. Perform a highway drive of 20+ minutes with RPM above 2500 to initiate automatic active regeneration."
            else -> "The Diesel Particulate Filter is clean. Current soot accumulation is low (${latest.dpfSootLevel}%), requiring no maintenance action."
        }
        val dpfColor = when {
            dpfScore <= 45 -> "#F44336"
            dpfScore <= 70 -> "#FFC107"
            else -> "#4CAF50"
        }

        // Overall Score is weighted average
        val overallScore = ((coolingScore * 0.25) + (lubricationScore * 0.25) + (electricalScore * 0.15) + (fuelScore * 0.20) + (dpfScore * 0.15)).toInt().coerceIn(0, 100)

        val summaryAr = when {
            overallScore >= 90 -> "بناءً على تحليل الاتجاهات التاريخية، فإن حالة محرك السيارة كيا كارنز CRDi ممتازة. جميع الأنظمة الحيوية تعمل بكفاءة عالية وضغوط وحرارة مستقرة. لا توجد تنبؤات بأي أعطال وشيكة المدى في غضون الـ 5000 كيلومتر القادمة."
            overallScore >= 70 -> "تم الكشف عن بعض الملاحظات وتراكمات الصيانة الخفيفة (مثل اقتراب عمر الزيت من نهايته أو تراكم سخام DPF متوسط). يوصى بإجراء التجديد الذاتي للفلتر وتغيير الزيت قريباً لتجنب انخفاض كفاءة الأداء أو حدوث انسداد في الفلتر."
            else -> "تحذير حاد: تم رصد مؤشرات حرجة في أداء المحرك (مثل السخونة المفرطة، انخفاض ضغط الزيت، عطل شحن الدينامو، أو انسداد كامل لفلتر DPF). يتنبأ النظام بوجود خطر تعطل وشيك جداً للأجزاء الداخلية للمحرك. ينصح بسحب السيارة لمركز فحص وصيانة مؤهل فوراً."
        }

        val summaryEn = when {
            overallScore >= 90 -> "Based on historical trend analysis, the overall condition of this Kia Carens CRDi engine is excellent. All vital systems operate within optimal parameters. No imminent failures or parts degradation are predicted for the next 5,000 km."
            overallScore >= 70 -> "Detected several minor maintenance triggers (e.g., aging engine oil or moderate DPF soot level). Performing a highway regeneration drive and replacing engine oil shortly is recommended to maintain optimal efficiency."
            else -> "CRITICAL ENGINE HEALTH WARNING: Urgent system failures detected (such as overheating, dangerously low oil pressure, alternator charging failure, or severe DPF blockage). Imminent mechanical failure predicted. Immediate professional maintenance is required."
        }

        val components = listOf(
            ComponentHealth("cooling", "نظام تبريد المحرك", "Engine Cooling System", coolingScore, coolingStatusAr, coolingStatusEn, coolingRecAr, coolingRecEn, coolingColor),
            ComponentHealth("lubrication", "نظام تزييت وزيت المحرك", "Engine Lubrication System", lubricationScore, lubStatusAr, lubStatusEn, lubRecAr, lubRecEn, lubColor),
            ComponentHealth("electrical", "النظام الكهربائي والمولد", "Electrical & Alternator", electricalScore, elecStatusAr, elecStatusEn, elecRecAr, elecRecEn, elecColor),
            ComponentHealth("fuel", "نظام حقن ديزل السكك المشتركة CRDi", "CRDi Fuel Injection System", fuelScore, fuelStatusAr, fuelStatusEn, fuelRecAr, fuelRecEn, fuelColor),
            ComponentHealth("dpf", "فلتر جزيئات الديزل DPF للبيئة", "Diesel Particulate Filter System", dpfScore, dpfStatusAr, dpfStatusEn, dpfRecAr, dpfRecEn, dpfColor)
        )

        return EngineHealthReport(
            overallScore = overallScore,
            components = components,
            analysisSummaryAr = summaryAr,
            analysisSummaryEn = summaryEn,
            lastAnalysisTimestamp = nowTime,
            isRealAi = false,
            servicePrediction = calculateLocalServicePrediction(currentData)
        )
    }

    suspend fun analyzeEngineHealthWithGemini(
        history: List<ObdSensorData>,
        currentData: ObdSensorData
    ): EngineHealthReport = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            Log.w("GeminiHealthPredictor", "Gemini API key is empty/placeholder, falling back to rule-based calculation.")
            return@withContext calculateLocalRuleHealth(history, currentData)
        }

        val trendBuilder = StringBuilder()
        trendBuilder.append("[\n")
        val allPoints = if (history.isEmpty()) listOf(currentData) else history
        allPoints.forEachIndexed { idx, pt ->
            trendBuilder.append("  {")
            trendBuilder.append("\"rpm\": ${pt.rpm}, ")
            trendBuilder.append("\"speed\": ${pt.speed}, ")
            trendBuilder.append("\"coolantTemp\": ${pt.coolantTemp}, ")
            trendBuilder.append("\"engineLoad\": ${pt.engineLoad}, ")
            trendBuilder.append("\"oilLifePercent\": ${pt.oilLifePercent}, ")
            trendBuilder.append("\"oilRemainingKm\": ${pt.oilRemainingKm}, ")
            trendBuilder.append("\"oilPressure\": ${pt.oilPressure}, ")
            trendBuilder.append("\"batteryVoltage\": ${pt.batteryVoltage}, ")
            trendBuilder.append("\"batteryStateOfCharge\": ${pt.batteryStateOfCharge}, ")
            trendBuilder.append("\"fuelPressure\": ${pt.fuelPressure}, ")
            trendBuilder.append("\"dpfSootLevel\": ${pt.dpfSootLevel}, ")
            trendBuilder.append("\"turboBoostPressure\": ${pt.turboBoostPressure}, ")
            val dtcs = pt.activeDtcs.joinToString(",") { it.code }
            trendBuilder.append("\"activeDtcs\": \"$dtcs\"")
            trendBuilder.append("}")
            if (idx < allPoints.size - 1) trendBuilder.append(",")
            trendBuilder.append("\n")
        }
        trendBuilder.append("]")

        val prompt = """
You are an expert automotive diagnostic AI specializing in the Kia Carens 2008 2.0 CRDi Turbo Diesel engine.
Analyze the following rolling historical OBD-II sensor data to detect subtle changes, anomalies, and degrading trends in key engine components, and output a detailed predictive maintenance health report including service intervals.

Historical Trend Data (ordered from oldest to newest):
${trendBuilder.toString()}

Generate an analysis in JSON format exactly matching this schema:
{
  "overallScore": 88,
  "components": [
    {
      "componentId": "cooling",
      "componentNameAr": "نظام تبريد المحرك",
      "componentNameEn": "Engine Cooling System",
      "score": 92,
      "statusAr": "سليم",
      "statusEn": "Healthy",
      "recommendationAr": "درجة حرارة مياه التبريد مستقرة عند 85 درجة مئوية. لا توجد مؤشرات على تهريب أو قصور.",
      "recommendationEn": "Coolant temperature is stable around 85°C. No signs of leakage or thermal degradation.",
      "colorHex": "#4CAF50"
    },
    {
      "componentId": "lubrication",
      "componentNameAr": "نظام التزييت وزيت المحرك",
      "componentNameEn": "Engine Lubrication System",
      "score": 85,
      "statusAr": "صيانة قريبة",
      "statusEn": "Maintenance Due",
      "recommendationAr": "عمر الزيت المتبقي 15%. ضغط الزيت سليم ولكن يوصى بتغيير الزيت والفلتر خلال 500 كم لتفادي اتساخ الصمامات.",
      "recommendationEn": "Remaining oil life is 15%. Oil pressure is healthy but oil and filter change is recommended within 500 km to prevent valve soot buildup.",
      "colorHex": "#FFC107"
    },
    {
      "componentId": "electrical",
      "componentNameAr": "النظام الكهربائي والمولد",
      "componentNameEn": "Electrical & Alternator",
      "score": 95,
      "statusAr": "سليم",
      "statusEn": "Healthy",
      "recommendationAr": "فولتية البطارية والشحن مستقرة ضمن الحدود السليمة.",
      "recommendationEn": "Battery voltage and charging output are stable and within normal range.",
      "colorHex": "#4CAF50"
    },
    {
      "componentId": "fuel",
      "componentNameAr": "نظام حقن ديزل السكك المشتركة CRDi",
      "componentNameEn": "CRDi Fuel Injection System",
      "score": 90,
      "statusAr": "سليم",
      "statusEn": "Healthy",
      "recommendationAr": "ضغط السكك المشتركة متجاوب وسليم.",
      "recommendationEn": "Common Rail pressure is responsive and normal.",
      "colorHex": "#4CAF50"
    },
    {
      "componentId": "dpf",
      "componentNameAr": "فلتر جزيئات الديزل DPF للبيئة",
      "componentNameEn": "Diesel Particulate Filter System",
      "score": 82,
      "statusAr": "تراكم سخام متوسط",
      "statusEn": "Moderate Soot",
      "recommendationAr": "مستوى السخام 52%. يوصى بقيادة السيارة في طريق سريع لتنظيف الفلتر ذاتيا.",
      "recommendationEn": "Soot level is 52%. A short highway drive is recommended for passive regeneration.",
      "colorHex": "#FFC107"
    }
  ],
  "analysisSummaryAr": "ملخص تحليلي باللغة العربية يشرح حالة المحرك والتنبؤات المستقبلية والأجزاء التي قد تتطلب فحصاً قريباً.",
  "analysisSummaryEn": "An English analytical summary explaining engine status, future predictions, and parts that may require near-term inspection.",
  "servicePrediction": {
    "oilChangeRemainingKm": 8500,
    "oilChangeRemainingDays": 242,
    "oilChangeConfidence": 95,
    "dieselFilterRemainingKm": 11200,
    "dieselFilterRemainingDays": 320,
    "dieselFilterConfidence": 85,
    "airFilterRemainingKm": 8200,
    "cabinFilterRemainingKm": 9400,
    "predictionExplanationAr": "بناءً على تذبذب ضغوط الديزل وتراكم سخام فلتر DPF التاريخي، يتوقع بقاء زيت المحرك وفلتر ديزل بحالة ممتازة حتى الفترات المذكورة.",
    "predictionExplanationEn": "Based on historical diesel injection pressures and DPF soot cycles, engine oil and diesel filter life is highly stable."
  }
}

Ensure to evaluate all 5 critical components listed in the components array AND the servicePrediction structure. Keep the JSON raw, perfectly formed, valid, and omit any markdown blocks like ```json or ```. Return ONLY the JSON object.
"""

        val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"
        
        val requestJson = JSONObject().apply {
            put("contents", JSONArray().apply {
                put(JSONObject().apply {
                    put("parts", JSONArray().apply {
                        put(JSONObject().apply {
                            put("text", prompt)
                        })
                    })
                })
            })
            put("generationConfig", JSONObject().apply {
                put("responseMimeType", "application/json")
                put("temperature", 0.1)
            })
        }

        val client = OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .build()

        val request = Request.Builder()
            .url(url)
            .post(requestJson.toString().toRequestBody("application/json; charset=utf-8".toMediaType()))
            .build()

        try {
            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    Log.e("GeminiHealthPredictor", "Gemini API failed with status code ${response.code}: ${response.message}")
                    return@withContext calculateLocalRuleHealth(history, currentData)
                }
                val responseBody = response.body?.string() ?: ""
                Log.d("GeminiHealthPredictor", "Gemini Response: $responseBody")
                
                val jsonResponse = JSONObject(responseBody)
                val candidates = jsonResponse.optJSONArray("candidates")
                val content = candidates?.optJSONObject(0)?.optJSONObject("content")
                val parts = content?.optJSONArray("parts")
                val responseText = parts?.optJSONObject(0)?.optString("text") ?: ""

                if (responseText.isNotEmpty()) {
                    parseEngineHealthReport(responseText, currentData, System.currentTimeMillis(), isRealAi = true)
                } else {
                    Log.e("GeminiHealthPredictor", "Gemini returned empty response text.")
                    calculateLocalRuleHealth(history, currentData)
                }
            }
        } catch (e: Exception) {
            Log.e("GeminiHealthPredictor", "Error calling Gemini API: ${e.message}", e)
            calculateLocalRuleHealth(history, currentData)
        }
    }
}
